from setuptools import setup, find_packages

setup(
    name="simulacra",
    version="0.1.0",
    description="Synthetic patient data generation. Useful to train AI models to be used for health and longevity applications. Synthetic data generation is still in its infancy, therefore synthetic data should NOT be used to validate the models or to infer their performance on real data.",
    author="Ferdinando Randisi",
    packages=find_packages(),
    install_requires=[
        # TODO: Automatically generated by ChatGPT - ensure these are relevant
        # TODO: currently, these are written both here and in requirements.txt - it'd be more robust to define them in requirements.txt and have them be ead from there instead. I should make sure that this is seen as a best practice, and do that.
        "numpy", "pandas", "scikit-learn", "faker", "pyyaml"
    ],
)
